#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home_page:
    path: /
    controller: App\Controller\HomePageController::getHomePage

user_register:
    path: /register
    controller: App\Controller\UserController::registerUser