#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#api_professionals:
#    path: /api/professionals
#    controller: App\Controller\ApiController::getProfessionals
#
#api_appointments:
#    path: /api/appointments
#    controller: App\Controller\ApiController::getAppointments
#
#api_unavailability:
#    path: /api/unavailability
#    controller: App\Controller\ApiController::getUnavailability
#
#api_users:
#    path: /api/users
#    controller: App\Controller\ApiController::getUsers

api_file:
    resource: '@GALIApiBundle/Resources/config/appointment_routing.yaml'
    prefix: '/api'
    
home_page:
    path: /{_locale}
    controller: App\Controller\HomePageController::getHomePage
    defaults:
        _locale: en

user_register:
    path: /{_locale}/register
    controller: App\Controller\UserController::registerUser
    defaults:
        _locale: en

login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login

logout:
    path: /logout

username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']

user_activate:
    path: /user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        token: '[a-z0-9-]+'
