#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_file:
    resource: '@GALIApiBundle/Resources/config/appointment_routing.yaml'
    prefix: '/api'
    
home_page:
    path: /
    controller: App\Controller\HomePageController::getHomePage

user_register:
    path: /register
    controller: App\Controller\UserController::registerUser

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout

username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']

user_activate:
    path: /user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        token: '[a-z0-9-]+'
