#index:
#    path: /
#    controller: App\Controller\DefaultController::index
angular:
    path: /angular
    controller: App\Controller\AngularController::index

home_page:
    path: /
    controller: App\Controller\HomePageController::getHomePage

api_professionals:
    path: /api/professionals
    controller: App\Controller\ApiController::getProfessionals

api_appointments:
    path: /api/appointments
    controller: App\Controller\ApiController::getAppointments
    
api_unavailability:
    path: /api/unavailability
    controller: App\Controller\ApiController::getUnavailability

api_users:
    path: /api/users
    controller: App\Controller\ApiController::getUsers

api_lastUser:
    path: /api/lastuser
    controller: App\Controller\ApiController::getLastUser

user_register:
    path: /register
    controller: App\Controller\UserController::registerUser

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout

username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']

user_activate:
    path: /user/activate/{token}
    controller: App\Controller\UserController::activateUser
    requirements:
        token: '[a-z0-9-]+'
