App\Entity\Appointment:
    type: entity
    table: appointment
    indexes:
        customer_idx:
            columns:
                - idcustomer
        pro_idx:
            columns:
                - idpro
    uniqueConstraints:
        idappointment_UNIQUE:
            columns:
                - idappointment
        idcustomer_UNIQUE:
            columns:
                - idcustomer
        idpro_UNIQUE:
            columns:
                - idpro
    id:
        idappointment:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            nullable: true
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        duration:
            type: time
            nullable: true
        approved:
            type: boolean
            nullable: true
    manyToOne:
        idcustomer:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcustomer:
                    referencedColumnName: iduser
            orphanRemoval: false
        idpro:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idpro:
                    referencedColumnName: iduser
            orphanRemoval: false
    lifecycleCallbacks: {  }
