App\Entity\Role:
    type: entity
    table: role
    uniqueConstraints:
        idrole_UNIQUE:
            columns:
                - idrole
    id:
        idrole:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
