App\Entity\Unavailability:
    type: entity
    table: unavailability
    indexes:
        user_idx:
            columns:
                - iduser
    uniqueConstraints:
        idunavailability_UNIQUE:
            columns:
                - idunavailability
        iduser_UNIQUE:
            columns:
                - iduser
    id:
        idunavailability:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        starttime:
            type: datetime
            nullable: true
        endtime:
            type: datetime
            nullable: true
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        iduser:
            targetEntity: User>unavailability
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iduser:
                    referencedColumnName: iduser
            orphanRemoval: false
    lifecycleCallbacks: {  }
