App\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        iduser_UNIQUE:
            columns:
                - iduser
    id:
        iduser:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: create_time
        active:
            type: boolean
            nullable: true
        token:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
