App\Entity\UserRole:
    type: entity
    table: user_role
    indexes:
        role_idx:
            columns:
                - iduser
                - idrole
        role:
            columns:
                - idrole
        IDX_2DE8C6A35E5C27E9:
            columns:
                - iduser
    uniqueConstraints:
        iduser_role_UNIQUE:
            columns:
                - iduser_role
    id:
        iduserRole:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: iduser_role
            generator:
                strategy: IDENTITY
    manyToOne:
        idrole:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idrole:
                    referencedColumnName: idrole
            orphanRemoval: false
        iduser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iduser:
                    referencedColumnName: iduser
            orphanRemoval: false
    lifecycleCallbacks: {  }
