version: '3.6'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - gali
    dns:
      - 127.0.0.1
    ports:
      - 3306:3306

  php:
    image: php:7.2-apache
    build: .
    volumes:
      - ./apache/apache.conf:/etc/apache2/apache.conf
      - ./apache/angular.conf:/etc/apache2/sites-enabled/angular.conf
      - ./apache/symfony.conf:/etc/apache2/sites-enabled/symfony.conf
      - ./apache/ports.conf:/etc/apache2/ports.conf      
      - ./../:/var/www/html/
    networks:
      - gali
    ports:
      - 80:80
      - 8080:8080

networks:
  gali:
    driver: bridge