version: '3.6'

services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - gali
    dns:
      - 127.0.0.1
    ports:
      - 3306:3306

  php:
    image: php:7.2-apache
    build: .
    volumes:
      - ./apache/apache.conf:/etc/apache2/apache2.conf
      - ./../:/var/www/html/
    networks:
      - gali
    ports:
      - 80:80

networks:
  gali:
    driver: bridge
