api_appointment_list:
    path: '/appointments'
    controller: GALI\ApiBundle\Controller\ApiController::getAppointments

api_appointment_create:
    path: '/appointment'
    controller: GALI\ApiBundle\Controller\ApiController::postAppointment

api_professionals:
   path: /api/professionals
   controller: GALI\ApiBundle\Controller\ApiController::getProfessionals

api_unavailability:
   path: /api/unavailability
   controller: GALI\ApiBundle\Controller\ApiController::getUnavailability

api_users:
   path: /api/users
   controller: GALI\ApiBundle\Controller\ApiController::getUsers