api_appointment_list:
    path: '/appointments'
    controller: GALI\ApiBundle\Controller\ApiController::getAppointments

api_appointment_create:
    path: '/appointment'
    controller: GALI\ApiBundle\Controller\ApiController::postAppointment

api_professionals_list:
    path: /professionals
    controller: GALI\ApiBundle\Controller\ApiController::getProfessionals

api_users_list:
    path: /users
    controller: GALI\ApiBundle\Controller\ApiController::getUsers