api_appointment_list:
    path: '/appointments'
    controller: GALI\ApiBundle\Controller\ApiController::getAppointments

api_appointment_create:
    path: '/appointment'
    controller: GALI\ApiBundle\Controller\ApiController::postAppointment

api_professionals:
   path: /professionals
   controller: GALI\ApiBundle\Controller\ApiController::getProfessionals

api_unavailability:
   path: /unavailability
   controller: GALI\ApiBundle\Controller\ApiController::getUnavailability

api_users:
   path: /users
   controller: GALI\ApiBundle\Controller\ApiController::getUsers