gali_api:
    groups:
        - "appointment.id"
        - "appointment.customer"
        - "appointment.professional"
        - "appointment.date"
        - "appointment.duration"
        - "appointment.description"
        - "appointment.approved"
        - "user.username"
